// Auto-generated by Glade# Code Generator
// http://eric.extremeboredom.net/projects/gladesharpcodegenerator/

using TaskManagerInterface;

namespace GanttMonoTracker.ExceptionPresentation
{
	using Gtk;
	using System;
	using System.IO;
	
	public class ExceptionViewDialog : IGuiMessageDialog
	{
		
		private Gtk.Dialog thisDialog;

		[Glade.Widget()]
		private Gtk.Label lbExceptionType;
		
		[Glade.Widget()]
		private Gtk.Label lbExceptionMessage;
		
		[Glade.Widget()]
		private Gtk.TextView tvExceptionDescription;
		
		[Glade.Widget()]
		private Gtk.TextView tvComment;
		
		[Glade.Widget()]
		private Gtk.TextView tvButtonDescription;
		
		[Glade.Widget()]
		private Gtk.HButtonBox hbuttonbox1;
		
		[Glade.Widget()]
		private Gtk.Button btnContinue;
		
		[Glade.Widget()]
		private Gtk.Button btnExit;
		
		[Glade.Widget()]
		private Gtk.Button btnSend;
		
		public ExceptionViewDialog(Exception exception, Window parent)
		{
			Stream stream = System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("ExceptionViewDialog.glade");
			Glade.XML glade = new Glade.XML(stream, "ExceptionViewDialog", null);
			stream.Close();
			glade.Autoconnect(this);
			thisDialog = ((Gtk.Dialog)(glade.GetWidget("ExceptionViewDialog")));
			thisDialog.TransientFor = parent;
			thisDialog.Modal = true;
			tvButtonDescription.Buffer.Text = "Use Cancel for continue [not recomended], Quit for exit program and Apply for send message to develop team";
			ExceptionType = exception.GetType().FullName;
			ExceptionMessage = exception.Message;
			ExceptionDescription = exception.StackTrace;
			tvButtonDescription.Sensitive = false;			 			
		}
		
		public int Run()
		{
			thisDialog.ShowAll();
			
			int result = 0;
			for (
			; true; 
			)
			{
				result = thisDialog.Run();
				if ((result != ((int)(Gtk.ResponseType.None))))
				{
					break;
				}
			}
			thisDialog.Destroy();
			return result;
		}
		
		#region IGuiMessageDialog Implementation  
		
		public int ShowDialog()
		{
			return Run();
		}
		
		public string Title
		{
			get
			{
				return thisDialog.Title;
			}
			set
			{
				thisDialog.Title = value;
			}
		}
		
		#endregion
		
		#region IDisposable Implementation
		
		public void Dispose()
		{
			thisDialog.Dispose();
		}
		
		#endregion
		
		public string ExceptionType
		{
			get
			{
				return lbExceptionType.Text; 
			}
			
			set
			{
				lbExceptionType.Text = value;
			}			
		}
		
		public string ExceptionMessage
		{
			get
			{
				return lbExceptionMessage.Text; 
			}
			
			set
			{
				lbExceptionMessage.Text = value;
			}			
		}
		
		public string ExceptionDescription
		{
			get
			{
				return tvExceptionDescription.Buffer.Text; 
			}
			
			set
			{
				tvExceptionDescription.Buffer.Text = value;
			}			
		}
		
		public string Comment
		{
			get
			{
				return tvComment.Buffer.Text; 
			}
			
			set
			{
				tvComment.Buffer.Text = value;
			}			
		}  

	}
	
}
